### ISSUE TITLE
Can we add language translation?

### ISSUE THREAD

**Issue by fatih5228** [X1Plus/X1Plus#275]
Can we add language translation?

I don't see the directory where the language packs are located

**Comment by balika011** [comment]
Yes. Ask @jwise for assistance.

**Comment by fatih5228** [comment]
> Ve@jphannifan, wiki sayfasını kim yazdı :-) https://github.com/X1Plus/X1Plus/wiki/Localization-Guide
> 
> @fatih5228 Hangi dile tercüme etmek istersiniz?

I am thinking of translating it into Turkish.

**Comment by jwise** [comment]
Turkish appears to be enabled for translation.  Feel free to start adding translations on CrowdIn!

**Comment by jphannifan** [comment]
I just enabled it earlier. Also updated the wiki yesterday

**Comment by jphannifan** [comment]
@fatih5228 You're making a ton of progress already! Since no one on our team can speak or read Turkish, we will need you or another Turkish user to complete the "proofreading" step. When you initially submit a translation, it goes to a list of translations that need to be approved. This really just involves resolving Crowdin's QA issues. 

You've probably noticed already that it's flagging lots of words as misspellings. There isn't really a great way to prevent this, but for my own translations I just go through these and fix any that are actual errors and click "Ignore" on the rest. 

Here's a screenshot of one of your translations as an example. You correctly excluded the apostrophe tag, so this error you just ignore, and as far as I can tell those 3 words have all been spelled correctly so you ignore those errors too.

<img width="400" alt="image" src="https://github.com/X1Plus/X1Plus/assets/149451641/807ac2c5-d396-4e3d-b356-1a2c3aa4f8cb">

As soon as you approve a translation, it will be ready to export and use in the UI. We don't have this step fully automated at this point, so when you get to this point, let me or Joshua know and we'll take care of the UI part.
