### ISSUE TITLE
Bed tilt orientation

### ISSUE THREAD

**Issue by Alkerion** [X1Plus/X1Plus#323]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. "Menu item *x* is confusing and always makes me do *y* by accident"
When we perform the bed diagnostic, we have the result reporting a bed tilt in X and Y, but we have no information about the orientation.
E.G. : Is front higher or lower than back ?
With the rather faint colors used to display highs and lows it's sometime quite difficult to decide which side we have to rise or lower.
![20240624_175823](https://github.com/X1Plus/X1Plus/assets/34811376/8a442d7d-fb81-4b24-abe8-190284d9c976)

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Ex. "Change menu item to be z instead"
Indicate which side is higher.

**Describe alternatives you've considered**
Also use less faint colors to see better the highs and lows.

**Software Information**
 - Current X1Plus Version: 2.0rc

**Comment by jwise** [comment]
In this case, it is intentional and the display is providing a graphical indication of the severity of the problem!  There is almost no tilt in your hotbed, and your bed is also very planar.  It is very intentional the the colors are faint in this case.  For severely warped or non-trammed beds, the colors are much brighter, but this display is designed to be truthful with how it communicates: your hotbed is as close to flat as it gets, and almost anything you do will make the problem worse, rather than better, so the software recommends that you should not try to change anything at all.
