### ISSUE TITLE
Dry Filament / Manual Operation of Chamber Fan and / or Auxillary Fan

### ISSUE THREAD

**Issue by GeorgWilli** [X1Plus/X1Plus#351]
**Is your feature request related to a problem? Please describe.**
When running the "Dry Filament" Tool, it is not possible to change the speeds of the
Chamber Fan and  Auxillary Fan in the Axes/Temperature Menu.
Weird things are happening : When setting the speed,
the speed is reset to 0 or even influencing the speed of the other fan.
I personally think it is useful to use the fans while drying, to get rid of the humidity in the chamber, ... 

**Describe the solution you'd like**
Possibility to manual activate / deactivate / set the speed in the Axes/Temperature Menu
during Drying Process.

**Describe alternatives you've considered**
Preset Speeds  of Chamber Fan and  Auxillary Fan in the Drying Filament Menu
And switching off after Drying time

**Software Information**
 - Current X1Plus Version: V2.0

** By the way : ** 
Congratulation to V2 !!!!   :-)
and especially the VNC Feature ! I really like this feature.

**Comment by jphannifan** [comment]
I think the first step here is coming up with a gcode macro that achieves the results you are looking for. `M140`, `M190`, and `M106` are the commands that control the hotbed and fans. 

Using Bambu's gcode placeholders and conditional statements, it may be possible to write this entirely in gcode, but this would be a good application for Python. There's a little sample macro here for reference https://github.com/X1Plus/X1Plus/blob/da11c3b61826fd78dff214b2a819bd45b0255ac8/images/cfw/usr/etc/macros/preheat.py

Since we don't plan on modifying the filament drying feature, I'm closing this, but if you come up with a gcode macro please share in a feature request!
